services:
  krakow-arcade-museum:
    image: krakow-arcade-museum
    build:
      context: .
      network: host
    ports:
      - "2222:2222"
    environment:
      FLAG: "hack4KrakCTF{u64_ticket_jackpot_after_hours}"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - SYS_CHROOT
    security_opt:
      - no-new-privileges:true
