services:
  ssl-cert:
    build: .
    image: ssl-cert
    networks:
      - ctf-services-net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ssl-cert.rule=Host(`kompletnie-niepodejrzana-strona.hack4krak.pl`)"
      - "traefik.http.services.ssl-cert.loadbalancer.server.port=80"

networks:
  ctf-services-net:
    external: true
    name: bridge
