$schema: "../schema.json"

id: "bibliotheca-jagellonica"
name: "Bibliotheca Jagellonica"
flag_hash: "3574d550186dcfea1ccdeb674f5ae871cc0a64400e44eafd5c241df30d3f5281"
difficulty_estimate: "hard"
labels:
  - "misc"
  - "web"

authors:
  - name: "Norbiros"
    url: "https://norbiros.dev"

task_release_phase: afternoon-day-1

display:
  # Biblioteka Jagiellonska
  icon_coordinates:
    x: 19.923611
    y: 50.060833
