services:
  casino:
    build: private/src
    image: casino:latest
    restart: unless-stopped
    networks:
      - ctf-services-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.casino.rule=Host(`casino.hack4krak.pl`)"
      - "traefik.http.services.casino.loadbalancer.server.port=3000"

    environment:
      - FLAG=hack4KrakCTF{n1e_0rg4n1z4t0rzy_n13_um13j4_t3g0_r0zw14z4c}

networks:
  ctf-services-net:
    external: true
    name: bridge